### ISSUE TITLE
Import feature not working

### ISSUE THREAD

**Issue by fatimaayman** [Daksitha/AvatarWithPersonality#5]
I was trying to import a json file with some animation, but I got the following error:

"Import finished.
Python: Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\CAfP\bone_motion.py", line 193, in execute
    bone_name = active_bone.basename
AttributeError: 'NoneType' object has no attribute 'basename'

location: C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py:132
Error: Python: Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\CAfP\bone_motion.py", line 193, in execute
    bone_name = active_bone.basename
AttributeError: 'NoneType' object has no attribute 'basename'

location: C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py:132

Python: Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\CAfP\file_op.py", line 63, in execute
    bpy.ops.cafp.boneanimator()
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\CAfP\bone_motion.py", line 193, in execute
    bone_name = active_bone.basename
AttributeError: 'NoneType' object has no attribute 'basename'

location: C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py:132

location: <unknown location>:-1"

**Comment by Daksitha** [comment]
Hi Fatima I have fixed the bug. Thanks for reporting
